### ISSUE TITLE
Add NANOAOD files to stica

### ISSUE THREAD

**Issue by lpernie** [cms-tamu/HHWWbb_analysis#1]
Add NANOAOD files to stica with teh addition of HME variable.
Useless branches  can be dropped, and very loose selection can be performed

**Comment by demarley** [comment]
Just to be clear, by "stica" you are referring to the machine in the lab named "cmstca"?

**Comment by lpernie** [comment]
yes, sorry for using that nickname, but i really liked it

**Comment by demarley** [comment]
No problem, I just wanted to make sure we were talking about the same thing.  Feel free to keep using "stica" :)

**Comment by demarley** [comment]
I think this is complete? @tahuang1991 you have ported all the samples over, right? (just waiting on bug fixed samples?)
