### ISSUE TITLE
Convert NANOAD + HME Flat Ntuples to RDD

### ISSUE THREAD

**Issue by lpernie** [cms-tamu/HHWWbb_analysis#2]
Need a script to save RDD so that they are our inputs for:
-  Analysis
-  Keras training

**Comment by lpernie** [comment]
Done with:
python FromMINIAOD_toRDD.py

(will be updated when real input root files will be available)

**Comment by demarley** [comment]
Hey @lpernie , just two small comments:

- I don't think lines like [this](https://github.com/cms-tamu/HHWWbb_analysis/blob/master/FromMINIAOD_toRDD.py#L4) are good.  I think it would be better to instead package stuff in functions or classes and then import them.  So instead, that line would read:
`import utilities.Samples_and_Functions as sf`  
and then you would access information like:
`TT_file = sf. files('TT') . # use a function to access the information`  
This makes it a little more clear what the code is accessing (and from where) for non-authors. 
- It might be cleaner to follow [convention](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) for how to write the name of files.  So `FromMINIAOD_toRDD.py` might be renamed `miniaod2rdd.py` or `miniAOD2RDD.py` (I would drop the "from", but that's just me).

EDIT: Fixed typo in "import" statement above

**Comment by lpernie** [comment]
Very good suggestions:
commit  https://github.com/cms-tamu/HHWWbb_analysis/commit/01d9acb9237996dd8b54d76095db9dc9c2c34b6e address your points.

**Comment by demarley** [comment]
Is this complete now, or are you waiting on the updated ntuples?

**Comment by lpernie** [comment]
We can already work with the current ones....  so feel free to add or edit things in current code.

**Comment by demarley** [comment]
Thanks @lpernie! I will go ahead and close this as complete
